//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waveface.Stream.WindowsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waveface.Stream.WindowsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg950\deff0\deflang1033\deflangfe1028{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li720\sl276\slmult1\b\f0\fs22 Download\b0  the app on your iOS/Android device.\par
        ///\b{\pntext\f0 2.\tab}Login\b0  to Stream\par
        ///{\pntext\f0 3.\tab}Connect to the same WiFi network as your PC. Your stream ap will enter \b Hyper Mode \b0 automatically\par
        ///\pard\li360\sl240\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string addDeviceInstruction {
            get {
                return ResourceManager.GetString("addDeviceInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have the latest version of Stream installed..
        /// </summary>
        internal static string ALREAD_UPDATED {
            get {
                return ResourceManager.GetString("ALREAD_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password. Please try again..
        /// </summary>
        internal static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password. Please try again..
        /// </summary>
        internal static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_appstore {
            get {
                object obj = ResourceManager.GetObject("button_appstore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_googleplay {
            get {
                object obj = ResourceManager.GetObject("button_googleplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CHECK_FOR_UPDATE {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        internal static string CHECKING_UPDATE {
            get {
                return ResourceManager.GetString("CHECKING_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove user account {0} from this computer?.
        /// </summary>
        internal static string CleanResourceMsg {
            get {
                return ResourceManager.GetString("CleanResourceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CLOSE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectingLogs.
        /// </summary>
        internal static string CollectingLogs {
            get {
                return ResourceManager.GetString("CollectingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Stream server.
        /// </summary>
        internal static string CONNECT_CLOUD_ERROR {
            get {
                return ResourceManager.GetString("CONNECT_CLOUD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Stream server.
        /// </summary>
        internal static string ConnectCloudError {
            get {
                return ResourceManager.GetString("ConnectCloudError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        internal static string DEFAULT_FONT {
            get {
                return ResourceManager.GetString("DEFAULT_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desktop_logo {
            get {
                object obj = ResourceManager.GetObject("desktop_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DOWNLOAD_INDICATOR {
            get {
                return ResourceManager.GetString("DOWNLOAD_INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dragNdrop_area {
            get {
                object obj = ResourceManager.GetObject("dragNdrop-area", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f_logo {
            get {
                object obj = ResourceManager.GetObject("f_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fb_btn {
            get {
                object obj = ResourceManager.GetObject("fb_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fb_btn_press {
            get {
                object obj = ResourceManager.GetObject("fb_btn_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Facebook account does not match the one used to create your Stream account. Please try again with another account..
        /// </summary>
        internal static string FB_CONNECT_FAILED {
            get {
                return ResourceManager.GetString("FB_CONNECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Facebook - Stream.
        /// </summary>
        internal static string FB_CONNECT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("FB_CONNECT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last synced with Facebook: {0}.
        /// </summary>
        internal static string FB_IMPORT_CLAST_SYNC_PATTERN {
            get {
                return ResourceManager.GetString("FB_IMPORT_CLAST_SYNC_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re currently importing your Facebook posts. You can chart the progress by refreshing your browser..
        /// </summary>
        internal static string FB_IMPRORT_PROGRESSING {
            get {
                return ResourceManager.GetString("FB_IMPRORT_PROGRESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FB_Logo {
            get {
                object obj = ResourceManager.GetObject("FB_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook token expired.
        /// </summary>
        internal static string FB_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("FB_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FBT_account {
            get {
                object obj = ResourceManager.GetObject("FBT_account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FBT_account_hl {
            get {
                object obj = ResourceManager.GetObject("FBT_account_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FBT_setting {
            get {
                object obj = ResourceManager.GetObject("FBT_setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FBT_setting_hl {
            get {
                object obj = ResourceManager.GetObject("FBT_setting_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must have data.
        /// </summary>
        internal static string FIELD_MUST_HAVE_DATA_PATTERN {
            get {
                return ResourceManager.GetString("FIELD_MUST_HAVE_DATA_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the fields!.
        /// </summary>
        internal static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import_photos_normal {
            get {
                object obj = ResourceManager.GetObject("import-photos_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import_photos_press {
            get {
                object obj = ResourceManager.GetObject("import-photos_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2} {3} photos, {4:0.##} {5}.
        /// </summary>
        internal static string INDICATOR_PATTERN {
            get {
                return ResourceManager.GetString("INDICATOR_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_box_2 {
            get {
                object obj = ResourceManager.GetObject("input_box_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_btn {
            get {
                object obj = ResourceManager.GetObject("login_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_btn_press {
            get {
                object obj = ResourceManager.GetObject("login_btn_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error. Please try again..
        /// </summary>
        internal static string LogInError {
            get {
                return ResourceManager.GetString("LogInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginMenuItem {
            get {
                return ResourceManager.GetString("LoginMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutMenuItem {
            get {
                return ResourceManager.GetString("LogoutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move.
        /// </summary>
        internal static string MOVE_FOLDER_UNSUCCESS {
            get {
                return ResourceManager.GetString("MOVE_FOLDER_UNSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move.
        /// </summary>
        internal static string MoveFolderUnsuccess {
            get {
                return ResourceManager.GetString("MoveFolderUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving....
        /// </summary>
        internal static string MOVING_RESOURCE_FOLDER {
            get {
                return ResourceManager.GetString("MOVING_RESOURCE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving....
        /// </summary>
        internal static string MovingResourceFolder {
            get {
                return ResourceManager.GetString("MovingResourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is out of date. Click ‘OK’ to download and install the latest version..
        /// </summary>
        internal static string NEED_UPGRADE {
            get {
                return ResourceManager.GetString("NEED_UPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is out of date. Click ‘OK’ to download and install the latest version..
        /// </summary>
        internal static string NeedToUpgrade {
            get {
                return ResourceManager.GetString("NeedToUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error.
        /// </summary>
        internal static string NETWORK_EXCEPTION {
            get {
                return ResourceManager.GetString("NETWORK_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        internal static string NETWORK_UNAVAILABLE {
            get {
                return ResourceManager.GetString("NETWORK_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newpost_btn {
            get {
                object obj = ResourceManager.GetObject("newpost_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newpost_btn_hl {
            get {
                object obj = ResourceManager.GetObject("newpost_btn_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NEXT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("NEXT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Stream.
        /// </summary>
        internal static string OPEN_STREAM {
            get {
                return ResourceManager.GetString("OPEN_STREAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P1 {
            get {
                object obj = ResourceManager.GetObject("P1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P2 {
            get {
                object obj = ResourceManager.GetObject("P2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P3 {
            get {
                object obj = ResourceManager.GetObject("P3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PersonalCloud {
            get {
                object obj = ResourceManager.GetObject("PersonalCloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PREVIOUS_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("PREVIOUS_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qr_waveface_site {
            get {
                object obj = ResourceManager.GetObject("qr_waveface_site", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Facebook connection has been disabled. Do you want to reconnect with Facebook..
        /// </summary>
        internal static string RECONNECT_MESSAGE {
            get {
                return ResourceManager.GetString("RECONNECT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string REMOVE_ACCOUNT_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_ACCOUNT_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account....
        /// </summary>
        internal static string REMOVE_ACCOUNT_MESSAGE {
            get {
                return ResourceManager.GetString("REMOVE_ACCOUNT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream service is not completely started. Please wait for a while and try again, or ensure the running status of Stream service..
        /// </summary>
        internal static string SERVICE_DOWN {
            get {
                return ResourceManager.GetString("SERVICE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause sync.
        /// </summary>
        internal static string SERVICE_PAUSE {
            get {
                return ResourceManager.GetString("SERVICE_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing sync....
        /// </summary>
        internal static string SERVICE_PAUSING {
            get {
                return ResourceManager.GetString("SERVICE_PAUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string SERVICE_QUIT {
            get {
                return ResourceManager.GetString("SERVICE_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume sync.
        /// </summary>
        internal static string SERVICE_RESUME {
            get {
                return ResourceManager.GetString("SERVICE_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming sync....
        /// </summary>
        internal static string SERVICE_RESUMING {
            get {
                return ResourceManager.GetString("SERVICE_RESUMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        internal static string SERVICE_RUNNING {
            get {
                return ResourceManager.GetString("SERVICE_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Stream server.
        /// </summary>
        internal static string SERVICE_START_FAIL {
            get {
                return ResourceManager.GetString("SERVICE_START_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Stream....
        /// </summary>
        internal static string SERVICE_STARTING {
            get {
                return ResourceManager.GetString("SERVICE_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync paused.
        /// </summary>
        internal static string SERVICE_STOP {
            get {
                return ResourceManager.GetString("SERVICE_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        internal static string SERVICE_SYNCING {
            get {
                return ResourceManager.GetString("SERVICE_SYNCING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup - Stream.
        /// </summary>
        internal static string SIGNUP_PAGE_TITLE {
            get {
                return ResourceManager.GetString("SIGNUP_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap software_update_available {
            get {
                object obj = ResourceManager.GetObject("software_update_available", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream service is not completely started. Please wait for a while and try again, or ensure the running status of Stream service..
        /// </summary>
        internal static string STATION_SERVICE_DOWN {
            get {
                return ResourceManager.GetString("STATION_SERVICE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream service is not completely started. Please wait for a while and try again, or ensure the running status of Stream service..
        /// </summary>
        internal static string StationServiceDown {
            get {
                return ResourceManager.GetString("StationServiceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_appstore_qr {
            get {
                object obj = ResourceManager.GetObject("stream_appstore_qr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_googleplay_qr {
            get {
                object obj = ResourceManager.GetObject("stream_googleplay_qr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_tray_init {
            get {
                object obj = ResourceManager.GetObject("stream_tray_init", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_tray_pause {
            get {
                object obj = ResourceManager.GetObject("stream_tray_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_tray_syncing1 {
            get {
                object obj = ResourceManager.GetObject("stream_tray_syncing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_tray_syncing2 {
            get {
                object obj = ResourceManager.GetObject("stream_tray_syncing2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_tray_warn {
            get {
                object obj = ResourceManager.GetObject("stream_tray_warn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_tray_working {
            get {
                object obj = ResourceManager.GetObject("stream_tray_working", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap streamfotocollector_icon_128 {
            get {
                object obj = ResourceManager.GetObject("streamfotocollector_icon_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap titlebar_1 {
            get {
                object obj = ResourceManager.GetObject("titlebar_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off.
        /// </summary>
        internal static string TURN_OFF {
            get {
                return ResourceManager.GetString("TURN_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        internal static string TURN_ON {
            get {
                return ResourceManager.GetString("TURN_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned Off.
        /// </summary>
        internal static string TURNED_OFF {
            get {
                return ResourceManager.GetString("TURNED_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned On.
        /// </summary>
        internal static string TURNED_ON {
            get {
                return ResourceManager.GetString("TURNED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred with our server. Please try again later. If the problem still occurs, please contact our support team at support@waveface.com.
        /// </summary>
        internal static string UNEXPECTED_EXCEPTION {
            get {
                return ResourceManager.GetString("UNEXPECTED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occur when remove account!.
        /// </summary>
        internal static string UNKNOW_REMOVEACCOUNT_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_REMOVEACCOUNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown signin error occur!.
        /// </summary>
        internal static string UNKNOW_SIGNIN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_SIGNIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown signup error occur!.
        /// </summary>
        internal static string UNKNOW_SIGNUP_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_SIGNUP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown signup error occur!.
        /// </summary>
        internal static string UNKNOW_SIGNUP_ERROR1 {
            get {
                return ResourceManager.GetString("UNKNOW_SIGNUP_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown signin error occur!.
        /// </summary>
        internal static string UnknownSigninError {
            get {
                return ResourceManager.GetString("UnknownSigninError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon UpdateAvailable {
            get {
                object obj = ResourceManager.GetObject("UpdateAvailable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UPLOAD_INDICATOR {
            get {
                return ResourceManager.GetString("UPLOAD_INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_en_1 {
            get {
                object obj = ResourceManager.GetObject("windows_en_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_en_2 {
            get {
                object obj = ResourceManager.GetObject("windows_en_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_zh_tw_1 {
            get {
                object obj = ResourceManager.GetObject("windows_zh_tw_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_zh_tw_2 {
            get {
                object obj = ResourceManager.GetObject("windows_zh_tw_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
