//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waveface.Stream.WindowsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waveface.Stream.WindowsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg950\deff0\deflang1033\deflangfe1028{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li720\sl276\slmult1\b\f0\fs22 Download\b0  the app on your iOS/Android device.\par
        ///\b{\pntext\f0 2.\tab}Login\b0  to Stream\par
        ///{\pntext\f0 3.\tab}Connect to the same WiFi network as your PC. Your stream ap will enter \b Hyper Mode \b0 automatically\par
        ///\pard\li360\sl240\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string addDeviceInstruction {
            get {
                return ResourceManager.GetString("addDeviceInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Data Synced.
        /// </summary>
        internal static string ALL_DATA_SYNCED {
            get {
                return ResourceManager.GetString("ALL_DATA_SYNCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have the latest version of AOStream installed..
        /// </summary>
        internal static string ALREAD_UPDATED {
            get {
                return ResourceManager.GetString("ALREAD_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password. Please try again..
        /// </summary>
        internal static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_appstore {
            get {
                object obj = ResourceManager.GetObject("button_appstore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_googleplay {
            get {
                object obj = ResourceManager.GetObject("button_googleplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CHECK_FOR_UPDATE {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        internal static string CHECKING_UPDATE {
            get {
                return ResourceManager.GetString("CHECKING_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Chrome Extension.
        /// </summary>
        internal static string CHROME_EXTENSION_MENU_ITEM {
            get {
                return ResourceManager.GetString("CHROME_EXTENSION_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove user account {0} from this computer?.
        /// </summary>
        internal static string CLEAN_RESOURCE_MSG_PATTERN {
            get {
                return ResourceManager.GetString("CLEAN_RESOURCE_MSG_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CLOSE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectingLogs.
        /// </summary>
        internal static string COLLECTING_LOGS {
            get {
                return ResourceManager.GetString("COLLECTING_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to AOStream server.
        /// </summary>
        internal static string CONNECT_CLOUD_ERROR {
            get {
                return ResourceManager.GetString("CONNECT_CLOUD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string CONTACT_US_MENU_ITEM {
            get {
                return ResourceManager.GetString("CONTACT_US_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        internal static string CONTROL_PREFERENCES_MENU_ITEM {
            get {
                return ResourceManager.GetString("CONTROL_PREFERENCES_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading indeces.
        /// </summary>
        internal static string DOWNLOAD_INDEX {
            get {
                return ResourceManager.GetString("DOWNLOAD_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DOWNLOAD_INDICATOR {
            get {
                return ResourceManager.GetString("DOWNLOAD_INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f_logo {
            get {
                object obj = ResourceManager.GetObject("f_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fb_btn {
            get {
                object obj = ResourceManager.GetObject("fb_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fb_btn_press {
            get {
                object obj = ResourceManager.GetObject("fb_btn_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account does not match the one used to create your AOStream account. Please try again with another account..
        /// </summary>
        internal static string FB_CONNECT_FAILED {
            get {
                return ResourceManager.GetString("FB_CONNECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with facebook.
        /// </summary>
        internal static string FB_CONNECT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("FB_CONNECT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last synced with Facebook: {0}.
        /// </summary>
        internal static string FB_IMPORT_CLAST_SYNC_PATTERN {
            get {
                return ResourceManager.GetString("FB_IMPORT_CLAST_SYNC_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re currently importing your Facebook posts. You can chart the progress by refreshing your browser..
        /// </summary>
        internal static string FB_IMPRORT_PROGRESSING {
            get {
                return ResourceManager.GetString("FB_IMPRORT_PROGRESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FB_Logo {
            get {
                object obj = ResourceManager.GetObject("FB_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Facebook connection has been disabled. Do you want to reconnect with Facebook..
        /// </summary>
        internal static string FB_RECONNECT_MESSAGE {
            get {
                return ResourceManager.GetString("FB_RECONNECT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook token expired.
        /// </summary>
        internal static string FB_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("FB_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must have data.
        /// </summary>
        internal static string FIELD_MUST_HAVE_DATA_PATTERN {
            get {
                return ResourceManager.GetString("FIELD_MUST_HAVE_DATA_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the fields!.
        /// </summary>
        internal static string FILL_ALL_FIELDS {
            get {
                return ResourceManager.GetString("FILL_ALL_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg950\deff0\nouicompat\deflang1033\deflangfe1028{\fonttbl{\f0\fnil\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.2.9200}\viewkind4\uc1 
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-284\li284\sa200\sl276\slmult1\cf1\b\fs18\lang1028 Unlimited\cf0\b0  number &amp; time for photos and web pages.\par
        ///{\pntext\f0 2.\tab}\cf1\b 500 MB \cf0\b0 of cloud storage for documents.\par
        ///{\pntext\f0 3.\tab}All original photos wil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FreePlan {
            get {
                return ResourceManager.GetString("FreePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Apps.
        /// </summary>
        internal static string GET_APPS_MENU_ITEM {
            get {
                return ResourceManager.GetString("GET_APPS_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        internal static string HELP_CENTER_MENU_ITEM {
            get {
                return ResourceManager.GetString("HELP_CENTER_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16 {
            get {
                object obj = ResourceManager.GetObject("icon_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16offline {
            get {
                object obj = ResourceManager.GetObject("icon_16x16offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import completed..
        /// </summary>
        internal static string IMPORT_DESC_DONE {
            get {
                return ResourceManager.GetString("IMPORT_DESC_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders.
        /// </summary>
        internal static string IMPORT_DESC_FOLDERS {
            get {
                return ResourceManager.GetString("IMPORT_DESC_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}, {1} task(s) queued..
        /// </summary>
        internal static string IMPORT_DESC_IN_PROGRESS_HAS_PENDING {
            get {
                return ResourceManager.GetString("IMPORT_DESC_IN_PROGRESS_HAS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}.
        /// </summary>
        internal static string IMPORT_DESC_IN_PROGRESS_NO_PENDING {
            get {
                return ResourceManager.GetString("IMPORT_DESC_IN_PROGRESS_NO_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to import next folder(s), {0} task(s) euqued..
        /// </summary>
        internal static string IMPORT_DESC_WAITING {
            get {
                return ResourceManager.GetString("IMPORT_DESC_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string IMPORT_MENU_ITEM {
            get {
                return ResourceManager.GetString("IMPORT_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2} {3} MB, {4:0.##} {5}.
        /// </summary>
        internal static string INDICATOR_PATTERN {
            get {
                return ResourceManager.GetString("INDICATOR_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_box_2 {
            get {
                object obj = ResourceManager.GetObject("input_box_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_btn {
            get {
                object obj = ResourceManager.GetObject("login_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_btn_press {
            get {
                object obj = ResourceManager.GetObject("login_btn_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error. Please try again..
        /// </summary>
        internal static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login....
        /// </summary>
        internal static string LOGIN_MENU_ITEM {
            get {
                return ResourceManager.GetString("LOGIN_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout....
        /// </summary>
        internal static string LOGOUT_MENU_ITEM {
            get {
                return ResourceManager.GetString("LOGOUT_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move.
        /// </summary>
        internal static string MOVE_FOLDER_UNSUCCESS {
            get {
                return ResourceManager.GetString("MOVE_FOLDER_UNSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving....
        /// </summary>
        internal static string MOVING_RESOURCE_FOLDER {
            get {
                return ResourceManager.GetString("MOVING_RESOURCE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is out of date. Click ‘OK’ to download and install the latest version..
        /// </summary>
        internal static string NEED_UPGRADE {
            get {
                return ResourceManager.GetString("NEED_UPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error.
        /// </summary>
        internal static string NETWORK_EXCEPTION {
            get {
                return ResourceManager.GetString("NETWORK_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        internal static string NETWORK_UNAVAILABLE {
            get {
                return ResourceManager.GetString("NETWORK_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NEXT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("NEXT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AOStream.
        /// </summary>
        internal static string OPEN_STREAM_MENU_ITEM {
            get {
                return ResourceManager.GetString("OPEN_STREAM_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P1 {
            get {
                object obj = ResourceManager.GetObject("P1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P2 {
            get {
                object obj = ResourceManager.GetObject("P2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P3 {
            get {
                object obj = ResourceManager.GetObject("P3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PersonalCloud {
            get {
                object obj = ResourceManager.GetObject("PersonalCloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PREVIOUS_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("PREVIOUS_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qr_waveface_site {
            get {
                object obj = ResourceManager.GetObject("qr_waveface_site", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string REMOVE_ACCOUNT_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_ACCOUNT_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account....
        /// </summary>
        internal static string REMOVE_ACCOUNT_MESSAGE {
            get {
                return ResourceManager.GetString("REMOVE_ACCOUNT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause sync.
        /// </summary>
        internal static string SERVICE_PAUSE {
            get {
                return ResourceManager.GetString("SERVICE_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause service.
        /// </summary>
        internal static string SERVICE_PAUSE_MENU_ITEM {
            get {
                return ResourceManager.GetString("SERVICE_PAUSE_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing sync....
        /// </summary>
        internal static string SERVICE_PAUSING {
            get {
                return ResourceManager.GetString("SERVICE_PAUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string SERVICE_QUIT {
            get {
                return ResourceManager.GetString("SERVICE_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume sync.
        /// </summary>
        internal static string SERVICE_RESUME {
            get {
                return ResourceManager.GetString("SERVICE_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume service.
        /// </summary>
        internal static string SERVICE_RESUME_MENU_ITEM {
            get {
                return ResourceManager.GetString("SERVICE_RESUME_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming sync....
        /// </summary>
        internal static string SERVICE_RESUMING {
            get {
                return ResourceManager.GetString("SERVICE_RESUMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to AOStream server.
        /// </summary>
        internal static string SERVICE_START_FAIL {
            get {
                return ResourceManager.GetString("SERVICE_START_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting AOStream....
        /// </summary>
        internal static string SERVICE_STARTING {
            get {
                return ResourceManager.GetString("SERVICE_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync paused.
        /// </summary>
        internal static string SERVICE_STOP {
            get {
                return ResourceManager.GetString("SERVICE_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        internal static string SERVICE_SYNCING {
            get {
                return ResourceManager.GetString("SERVICE_SYNCING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup - AOStream.
        /// </summary>
        internal static string SIGNUP_PAGE_TITLE {
            get {
                return ResourceManager.GetString("SIGNUP_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap software_update_available {
            get {
                object obj = ResourceManager.GetObject("software_update_available", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOStream service is not completely started. Please wait for a while and try again, or ensure the running status of AOStream service..
        /// </summary>
        internal static string STATION_SERVICE_DOWN {
            get {
                return ResourceManager.GetString("STATION_SERVICE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_appstore_qr {
            get {
                object obj = ResourceManager.GetObject("stream_appstore_qr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stream_googleplay_qr {
            get {
                object obj = ResourceManager.GetObject("stream_googleplay_qr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap streamfotocollector_icon_128 {
            get {
                object obj = ResourceManager.GetObject("streamfotocollector_icon_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TBD] AOStream collects your check-ins and web links you liked or shared..
        /// </summary>
        internal static string SVC_FACEBOOK_DESC {
            get {
                return ResourceManager.GetString("SVC_FACEBOOK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TBD] AOStream collects starred articles in Google Reader..
        /// </summary>
        internal static string SVC_GOOGLE_DESC {
            get {
                return ResourceManager.GetString("SVC_GOOGLE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TBD] Your favorite or retwitted web pages will be collected in AOStream..
        /// </summary>
        internal static string SVC_TWITTER_DESC {
            get {
                return ResourceManager.GetString("SVC_TWITTER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected locally.
        /// </summary>
        internal static string SYNC_CONNECTED_LOCALLY {
            get {
                return ResourceManager.GetString("SYNC_CONNECTED_LOCALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync error: .
        /// </summary>
        internal static string SYNC_ERROR {
            get {
                return ResourceManager.GetString("SYNC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen at {0}.
        /// </summary>
        internal static string SYNC_LAST_SEEN {
            get {
                return ResourceManager.GetString("SYNC_LAST_SEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline ({0}).
        /// </summary>
        internal static string SYNC_OFFLINE {
            get {
                return ResourceManager.GetString("SYNC_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing with Cloud.
        /// </summary>
        internal static string SYNCING_WITH_CLOUD {
            get {
                return ResourceManager.GetString("SYNCING_WITH_CLOUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off.
        /// </summary>
        internal static string TURN_OFF {
            get {
                return ResourceManager.GetString("TURN_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        internal static string TURN_ON {
            get {
                return ResourceManager.GetString("TURN_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned Off.
        /// </summary>
        internal static string TURNED_OFF {
            get {
                return ResourceManager.GetString("TURNED_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned On.
        /// </summary>
        internal static string TURNED_ON {
            get {
                return ResourceManager.GetString("TURNED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred with our server. Please try again later. If the problem still occurs, please contact our support team at support@waveface.com.
        /// </summary>
        internal static string UNEXPECTED_EXCEPTION {
            get {
                return ResourceManager.GetString("UNEXPECTED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occur when remove account!.
        /// </summary>
        internal static string UNKNOW_REMOVEACCOUNT_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_REMOVEACCOUNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown signin error occur!.
        /// </summary>
        internal static string UNKNOW_SIGNIN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_SIGNIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown signup error occur!.
        /// </summary>
        internal static string UNKNOW_SIGNUP_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_SIGNUP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon UpdateAvailable {
            get {
                object obj = ResourceManager.GetObject("UpdateAvailable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UPLOAD_INDICATOR {
            get {
                return ResourceManager.GetString("UPLOAD_INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_en_1 {
            get {
                object obj = ResourceManager.GetObject("windows_en_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_en_2 {
            get {
                object obj = ResourceManager.GetObject("windows_en_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_zh_tw_1 {
            get {
                object obj = ResourceManager.GetObject("windows_zh_tw_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_zh_tw_2 {
            get {
                object obj = ResourceManager.GetObject("windows_zh_tw_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
