//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waveface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waveface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap account_badge {
            get {
                object obj = ResourceManager.GetObject("account_badge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap account_badge_hl {
            get {
                object obj = ResourceManager.GetObject("account_badge_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        internal static string ACCOUNT_TOOL_TIP {
            get {
                return ResourceManager.GetString("ACCOUNT_TOOL_TIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap add_photo {
            get {
                object obj = ResourceManager.GetObject("add_photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AllTime {
            get {
                object obj = ResourceManager.GetObject("AllTime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_divide {
            get {
                object obj = ResourceManager.GetObject("arrow_divide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowCircleDouble {
            get {
                object obj = ResourceManager.GetObject("ArrowCircleDouble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this post?.
        /// </summary>
        internal static string ASK_REMOVE_POST {
            get {
                return ResourceManager.GetString("ASK_REMOVE_POST", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_hl {
            get {
                object obj = ResourceManager.GetObject("back_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Edit.
        /// </summary>
        internal static string CANCEL_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CANCEL_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Post.
        /// </summary>
        internal static string CANCEL_POST_TITLE {
            get {
                return ResourceManager.GetString("CANCEL_POST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover image changed successfully..
        /// </summary>
        internal static string CHANGED_COVER_IMAGE {
            get {
                return ResourceManager.GetString("CHANGED_COVER_IMAGE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cloud {
            get {
                object obj = ResourceManager.GetObject("Cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap content {
            get {
                object obj = ResourceManager.GetObject("content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cover {
            get {
                object obj = ResourceManager.GetObject("cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cover_hl {
            get {
                object obj = ResourceManager.GetObject("cover_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Image.
        /// </summary>
        internal static string COVER_IMAGE {
            get {
                return ResourceManager.GetString("COVER_IMAGE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CoverImage {
            get {
                object obj = ResourceManager.GetObject("CoverImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        internal static string DEFAULT_FONT {
            get {
                return ResourceManager.GetString("DEFAULT_FONT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap desktop_logo {
            get {
                object obj = ResourceManager.GetObject("desktop_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        internal static string DISCARD_EDIT_POST {
            get {
                return ResourceManager.GetString("DISCARD_EDIT_POST", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dragdrop_tutorial {
            get {
                object obj = ResourceManager.GetObject("dragdrop_tutorial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dragNdrop_area1 {
            get {
                object obj = ResourceManager.GetObject("dragNdrop_area1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dragNdrop_loading0 {
            get {
                object obj = ResourceManager.GetObject("dragNdrop_loading0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment text box is empty!.
        /// </summary>
        internal static string EMPTY_COMMENT {
            get {
                return ResourceManager.GetString("EMPTY_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text cannot be empty!.
        /// </summary>
        internal static string EMPTY_CONTENT {
            get {
                return ResourceManager.GetString("EMPTY_CONTENT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please try again..
        /// </summary>
        internal static string ERROR_AND_RETRY {
            get {
                return ResourceManager.GetString("ERROR_AND_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authentication has expired. Re-enter your password to login again..
        /// </summary>
        internal static string EXCEPTION_401 {
            get {
                return ResourceManager.GetString("EXCEPTION_401", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fastforward {
            get {
                object obj = ResourceManager.GetObject("fastforward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string FAVORITE {
            get {
                return ResourceManager.GetString("FAVORITE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FB_blue_btn {
            get {
                object obj = ResourceManager.GetObject("FB_blue_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_blue_btn_2 {
            get {
                object obj = ResourceManager.GetObject("FB_blue_btn_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_blue_btn_hl {
            get {
                object obj = ResourceManager.GetObject("FB_blue_btn_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_blue_btn_hl_2 {
            get {
                object obj = ResourceManager.GetObject("FB_blue_btn_hl_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Facebook account does not match the one used to create your Stream account. Please try again with another account..
        /// </summary>
        internal static string FB_CONNECT_FAILED {
            get {
                return ResourceManager.GetString("FB_CONNECT_FAILED", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FB_cover {
            get {
                object obj = ResourceManager.GetObject("FB_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_cover_hl {
            get {
                object obj = ResourceManager.GetObject("FB_cover_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_creat_btn {
            get {
                object obj = ResourceManager.GetObject("FB_creat_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_creat_btn_hl {
            get {
                object obj = ResourceManager.GetObject("FB_creat_btn_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_edit {
            get {
                object obj = ResourceManager.GetObject("FB_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_edit_add_photo {
            get {
                object obj = ResourceManager.GetObject("FB_edit_add_photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_edit_delete {
            get {
                object obj = ResourceManager.GetObject("FB_edit_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_edit_footnote {
            get {
                object obj = ResourceManager.GetObject("FB_edit_footnote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_edit_footnote_hl {
            get {
                object obj = ResourceManager.GetObject("FB_edit_footnote_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_edit_hl {
            get {
                object obj = ResourceManager.GetObject("FB_edit_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_fav {
            get {
                object obj = ResourceManager.GetObject("FB_fav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_fav_hl {
            get {
                object obj = ResourceManager.GetObject("FB_fav_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last synced with Facebook: {0}.
        /// </summary>
        internal static string FB_IMPORT_CLAST_SYNC_PATTERN {
            get {
                return ResourceManager.GetString("FB_IMPORT_CLAST_SYNC_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re currently importing your Facebook posts. You can chart the progress by refreshing your browser..
        /// </summary>
        internal static string FB_IMPRORT_PROGRESSING {
            get {
                return ResourceManager.GetString("FB_IMPRORT_PROGRESSING", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FB_info {
            get {
                object obj = ResourceManager.GetObject("FB_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_info_hl {
            get {
                object obj = ResourceManager.GetObject("FB_info_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_moreoption {
            get {
                object obj = ResourceManager.GetObject("FB_moreoption", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_moreoption_hl {
            get {
                object obj = ResourceManager.GetObject("FB_moreoption_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_newpost {
            get {
                object obj = ResourceManager.GetObject("FB_newpost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_newpost_btn {
            get {
                object obj = ResourceManager.GetObject("FB_newpost_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_newpost_btn_hl {
            get {
                object obj = ResourceManager.GetObject("FB_newpost_btn_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_newpost_hl {
            get {
                object obj = ResourceManager.GetObject("FB_newpost_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_openin {
            get {
                object obj = ResourceManager.GetObject("FB_openin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_openin_hl {
            get {
                object obj = ResourceManager.GetObject("FB_openin_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_refresh {
            get {
                object obj = ResourceManager.GetObject("FB_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_refresh_hl {
            get {
                object obj = ResourceManager.GetObject("FB_refresh_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_remove {
            get {
                object obj = ResourceManager.GetObject("FB_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_remove_hl {
            get {
                object obj = ResourceManager.GetObject("FB_remove_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_remove_post {
            get {
                object obj = ResourceManager.GetObject("FB_remove_post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_remove_post_hl {
            get {
                object obj = ResourceManager.GetObject("FB_remove_post_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_save {
            get {
                object obj = ResourceManager.GetObject("FB_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_save_hl {
            get {
                object obj = ResourceManager.GetObject("FB_save_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_saveall {
            get {
                object obj = ResourceManager.GetObject("FB_saveall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_saveall_hl {
            get {
                object obj = ResourceManager.GetObject("FB_saveall_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_setting {
            get {
                object obj = ResourceManager.GetObject("FB_setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_setting_hl {
            get {
                object obj = ResourceManager.GetObject("FB_setting_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_slide {
            get {
                object obj = ResourceManager.GetObject("FB_slide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_slide_hl {
            get {
                object obj = ResourceManager.GetObject("FB_slide_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_slide1 {
            get {
                object obj = ResourceManager.GetObject("FB_slide1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_slide1_hl {
            get {
                object obj = ResourceManager.GetObject("FB_slide1_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_today_btn {
            get {
                object obj = ResourceManager.GetObject("FB_today_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_today_btn_hl {
            get {
                object obj = ResourceManager.GetObject("FB_today_btn_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook token expired.
        /// </summary>
        internal static string FB_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("FB_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FB_unfav {
            get {
                object obj = ResourceManager.GetObject("FB_unfav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_unfav_hl {
            get {
                object obj = ResourceManager.GetObject("FB_unfav_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_account {
            get {
                object obj = ResourceManager.GetObject("FBT_account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_account_hl {
            get {
                object obj = ResourceManager.GetObject("FBT_account_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_newpost {
            get {
                object obj = ResourceManager.GetObject("FBT_newpost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_newpost_hl_hl {
            get {
                object obj = ResourceManager.GetObject("FBT_newpost_hl_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_refresh {
            get {
                object obj = ResourceManager.GetObject("FBT_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_refresh_hl {
            get {
                object obj = ResourceManager.GetObject("FBT_refresh_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_setting {
            get {
                object obj = ResourceManager.GetObject("FBT_setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FBT_setting_hl {
            get {
                object obj = ResourceManager.GetObject("FBT_setting_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must have data.
        /// </summary>
        internal static string FIELD_MUST_HAVE_DATA_PATTERN {
            get {
                return ResourceManager.GetString("FIELD_MUST_HAVE_DATA_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo does not exist: [{0}].
        ///        1.Click &apos;Continue&apos;, to skip this file.
        ///        2.Click &apos;Retry&apos;, to try again.
        ///        3.Click &apos;Cancel&apos;, to discard post..
        /// </summary>
        internal static string FILE_MISS_PATTERN {
            get {
                return ResourceManager.GetString("FILE_MISS_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all the fields!.
        /// </summary>
        internal static string FILL_ALL_FIELDS {
            get {
                return ResourceManager.GetString("FILL_ALL_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your password to login again..
        /// </summary>
        internal static string FORCE_LOGOUT {
            get {
                return ResourceManager.GetString("FORCE_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the web preview for.
        /// </summary>
        internal static string GET_WEB_PREVIEW {
            get {
                return ResourceManager.GetString("GET_WEB_PREVIEW", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gridview {
            get {
                object obj = ResourceManager.GetObject("gridview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gridview_hl {
            get {
                object obj = ResourceManager.GetObject("gridview_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid image file: .
        /// </summary>
        internal static string INVAILD_IMAGE {
            get {
                return ResourceManager.GetString("INVAILD_IMAGE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LD {
            get {
                object obj = ResourceManager.GetObject("LD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb {
            get {
                object obj = ResourceManager.GetObject("lightbulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoadingImage {
            get {
                object obj = ResourceManager.GetObject("LoadingImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In error. Please try again..
        /// </summary>
        internal static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logout_btn {
            get {
                object obj = ResourceManager.GetObject("logout_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logout_btn_press {
            get {
                object obj = ResourceManager.GetObject("logout_btn_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Magnifier {
            get {
                object obj = ResourceManager.GetObject("Magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MD {
            get {
                object obj = ResourceManager.GetObject("MD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // minmax.js: make IE5+/Win support CSS min/max-width/height
        ///// version 1.0, 08-Aug-2003
        ///// written by Andrew Clover &lt;and@doxdesk.com&gt;, use freely
        ///
        ////*@cc_on
        ///@if (@_win32 &amp;&amp; @_jscript_version&gt;4)
        ///
        ///var minmax_elements;
        ///
        ///minmax_props= new Array(
        ///  new Array(&apos;min-width&apos;, &apos;minWidth&apos;),
        ///  new Array(&apos;max-width&apos;, &apos;maxWidth&apos;),
        ///  new Array(&apos;min-height&apos;,&apos;minHeight&apos;),
        ///  new Array(&apos;max-height&apos;,&apos;maxHeight&apos;)
        ///);
        ///
        ///// Binding. Called on all new elements. If &lt;body&gt;, initialise; check all
        ///// elements for minmax  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string minmax {
            get {
                return ResourceManager.GetString("minmax", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Close {
            get {
                object obj = ResourceManager.GetObject("MMC_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Close_hl {
            get {
                object obj = ResourceManager.GetObject("MMC_Close_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Max {
            get {
                object obj = ResourceManager.GetObject("MMC_Max", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Max_hl {
            get {
                object obj = ResourceManager.GetObject("MMC_Max_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Min {
            get {
                object obj = ResourceManager.GetObject("MMC_Min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Min_hl {
            get {
                object obj = ResourceManager.GetObject("MMC_Min_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Restore {
            get {
                object obj = ResourceManager.GetObject("MMC_Restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMC_Restore_hl {
            get {
                object obj = ResourceManager.GetObject("MMC_Restore_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Month {
            get {
                object obj = ResourceManager.GetObject("Month", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is out of date. Click ‘OK’ to download and install the latest version..
        /// </summary>
        internal static string NEED_UPGRADE {
            get {
                return ResourceManager.GetString("NEED_UPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Disconnected..
        /// </summary>
        internal static string NETWORK_DISCONNECTED {
            get {
                return ResourceManager.GetString("NETWORK_DISCONNECTED", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap network_error {
            get {
                object obj = ResourceManager.GetObject("network_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error.
        /// </summary>
        internal static string NETWORK_EXCEPTION {
            get {
                return ResourceManager.GetString("NETWORK_EXCEPTION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap network_receive {
            get {
                object obj = ResourceManager.GetObject("network_receive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        internal static string NETWORK_UNAVAILABLE {
            get {
                return ResourceManager.GetString("NETWORK_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No web preview for.
        /// </summary>
        internal static string NO_WEB_PREVIEW {
            get {
                return ResourceManager.GetString("NO_WEB_PREVIEW", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ObjectPosition {
            get {
                object obj = ResourceManager.GetObject("ObjectPosition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ObjectSize {
            get {
                object obj = ResourceManager.GetObject("ObjectSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reached your monthly upload limit. 
        ///        1.Click &apos;Retry&apos;, to try again. 
        ///        2.Click &apos;Cancel&apos;, to discard post..
        /// </summary>
        internal static string OVER_QUOTA {
            get {
                return ResourceManager.GetString("OVER_QUOTA", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        internal static string PHOTO {
            get {
                return ResourceManager.GetString("PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file (*{0})|*{1}.
        /// </summary>
        internal static string PHOTO_SAVE_FILTER_PATTERN {
            get {
                return ResourceManager.GetString("PHOTO_SAVE_FILTER_PATTERN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap photo_spinner {
            get {
                object obj = ResourceManager.GetObject("photo_spinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync in progress....
        /// </summary>
        internal static string PHOTO_UPLOADING {
            get {
                return ResourceManager.GetString("PHOTO_UPLOADING", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap photoadded_badge {
            get {
                object obj = ResourceManager.GetObject("photoadded_badge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        internal static string PHOTOS {
            get {
                return ResourceManager.GetString("PHOTOS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Post {
            get {
                object obj = ResourceManager.GetObject("Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Error!.
        /// </summary>
        internal static string POST_ERROR {
            get {
                return ResourceManager.GetString("POST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Preview ({0} photo(s) added).
        /// </summary>
        internal static string POST_PHOTO_SUMMARY_PATTERN {
            get {
                return ResourceManager.GetString("POST_PHOTO_SUMMARY_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post success!.
        /// </summary>
        internal static string POST_SUCCESS {
            get {
                return ResourceManager.GetString("POST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to add?.
        /// </summary>
        internal static string PURE_TEXT_COMMENT_WATER_MARK {
            get {
                return ResourceManager.GetString("PURE_TEXT_COMMENT_WATER_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your description here....
        /// </summary>
        internal static string PURE_TEXT_WATER_MARK {
            get {
                return ResourceManager.GetString("PURE_TEXT_WATER_MARK", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RD {
            get {
                object obj = ResourceManager.GetObject("RD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Facebook connection has been disabled. Do you want to reconnect with Facebook..
        /// </summary>
        internal static string RECONNECT_MESSAGE {
            get {
                return ResourceManager.GetString("RECONNECT_MESSAGE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh_hl {
            get {
                object obj = ResourceManager.GetObject("refresh_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_hl2 {
            get {
                object obj = ResourceManager.GetObject("refresh_hl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_hl3 {
            get {
                object obj = ResourceManager.GetObject("refresh_hl3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_hl4 {
            get {
                object obj = ResourceManager.GetObject("refresh_hl4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_hl5 {
            get {
                object obj = ResourceManager.GetObject("refresh_hl5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string REFRESH_TOOL_TIP {
            get {
                return ResourceManager.GetString("REFRESH_TOOL_TIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh2 {
            get {
                object obj = ResourceManager.GetObject("refresh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh3 {
            get {
                object obj = ResourceManager.GetObject("refresh3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh4 {
            get {
                object obj = ResourceManager.GetObject("refresh4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh5 {
            get {
                object obj = ResourceManager.GetObject("refresh5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Station is no longer available because &apos;{0}&apos; setup a new station or the account does not exist anymore.
        ///Please restart the program to initialize Stream Station..
        /// </summary>
        internal static string REGISTERED_REQUIRED_PATTERN {
            get {
                return ResourceManager.GetString("REGISTERED_REQUIRED_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove all files?.
        /// </summary>
        internal static string REMOVE_ALL_FILES {
            get {
                return ResourceManager.GetString("REMOVE_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove selected file(s)?.
        /// </summary>
        internal static string REMOVE_SELECTED_FILES {
            get {
                return ResourceManager.GetString("REMOVE_SELECTED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Post.
        /// </summary>
        internal static string REMOVE_TOOL_TIP {
            get {
                return ResourceManager.GetString("REMOVE_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rewind {
            get {
                object obj = ResourceManager.GetObject("rewind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images are saved..
        /// </summary>
        internal static string SAVE_ALL_OK {
            get {
                return ResourceManager.GetString("SAVE_ALL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Save Error!.
        /// </summary>
        internal static string SAVE_ERROR {
            get {
                return ResourceManager.GetString("SAVE_ERROR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save_hl {
            get {
                object obj = ResourceManager.GetObject("save_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save1 {
            get {
                object obj = ResourceManager.GetObject("Save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveAll {
            get {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap script {
            get {
                object obj = ResourceManager.GetObject("script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scriptedit {
            get {
                object obj = ResourceManager.GetObject("scriptedit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location to save files.
        /// </summary>
        internal static string SELECT_SAVE_PATH {
            get {
                return ResourceManager.GetString("SELECT_SAVE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string SETTING_TOOL_TIP {
            get {
                return ResourceManager.GetString("SETTING_TOOL_TIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap skin {
            get {
                object obj = ResourceManager.GetObject("skin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slide {
            get {
                object obj = ResourceManager.GetObject("slide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slide_hl {
            get {
                object obj = ResourceManager.GetObject("slide_hl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlideShow {
            get {
                object obj = ResourceManager.GetObject("SlideShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Station {
            get {
                object obj = ResourceManager.GetObject("Station", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Station service is not completely started. Please wait for a while and try again, or ensure the running status of Stream Station windows service..
        /// </summary>
        internal static string STATION_SERVICE_DOWN {
            get {
                return ResourceManager.GetString("STATION_SERVICE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error.
        /// </summary>
        internal static string SYSTEM_ERROR_TITLE {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_TITLE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TickCircle {
            get {
                object obj = ResourceManager.GetObject("TickCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap timebar {
            get {
                object obj = ResourceManager.GetObject("timebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap titlebar_1 {
            get {
                object obj = ResourceManager.GetObject("titlebar_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap titlebar_2 {
            get {
                object obj = ResourceManager.GetObject("titlebar_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap titlebar_3 {
            get {
                object obj = ResourceManager.GetObject("titlebar_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap titlebar_4 {
            get {
                object obj = ResourceManager.GetObject("titlebar_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToLeft {
            get {
                object obj = ResourceManager.GetObject("ToLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off.
        /// </summary>
        internal static string TURN_OFF {
            get {
                return ResourceManager.GetString("TURN_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        internal static string TURN_ON {
            get {
                return ResourceManager.GetString("TURN_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned Off.
        /// </summary>
        internal static string TURNED_OFF {
            get {
                return ResourceManager.GetString("TURNED_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned On.
        /// </summary>
        internal static string TURNED_ON {
            get {
                return ResourceManager.GetString("TURNED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to post. Please try again..
        /// </summary>
        internal static string UNABLE_POST {
            get {
                return ResourceManager.GetString("UNABLE_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred with our server. Please try again later. If the problem still occurs, please contact our support team at support@waveface.com.
        /// </summary>
        internal static string UNEXPECTED_EXCEPTION {
            get {
                return ResourceManager.GetString("UNEXPECTED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        internal static string UNFAVORITE {
            get {
                return ResourceManager.GetString("UNFAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via.
        /// </summary>
        internal static string VIA {
            get {
                return ResourceManager.GetString("VIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web link preview for.
        /// </summary>
        internal static string WEB_PREVIEW_COME_FROM {
            get {
                return ResourceManager.GetString("WEB_PREVIEW_COME_FROM", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap webcam {
            get {
                object obj = ResourceManager.GetObject("webcam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html, body, div, span, object, iframe,
        ///h1, h2, h3, h4, h5, h6, p, blockquote, pre,
        ///a, abbr, acronym, address, code,
        ///del, dfn, em, img, q, dl, dt, dd, ol, ul, li,
        ///fieldset, form, label, legend,
        ///table, caption, tbody, tfoot, thead, tr, th, td {
        ///  margin: 0;
        ///  padding: 0;
        ///  border: 0;
        ///  font-weight: inherit;
        ///  font-style: inherit;
        ///  font-size: 100%;
        ///  font-family: inherit;
        ///  vertical-align: baseline;
        ///}
        ///
        ///
        ////* Tables still need &apos;cellspacing=&quot;0&quot;&apos; in the markup. */
        ///table { border-collapse: separat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WFPreviewWin {
            get {
                return ResourceManager.GetString("WFPreviewWin", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap white_edit {
            get {
                object obj = ResourceManager.GetObject("white_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap write_comment {
            get {
                object obj = ResourceManager.GetObject("write_comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
