//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.239
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manina.Windows.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageListViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageListViewResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manina.Windows.Forms.ImageListViewResources", typeof(ImageListViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Aperture 的當地語系化字串。
        /// </summary>
        internal static string Aperture {
            get {
                return ResourceManager.GetString("Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Artist 的當地語系化字串。
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copyright 的當地語系化字串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom 的當地語系化字串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last Access 的當地語系化字串。
        /// </summary>
        internal static string DateAccessed {
            get {
                return ResourceManager.GetString("DateAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Created 的當地語系化字串。
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modified 的當地語系化字串。
        /// </summary>
        internal static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Taken 的當地語系化字串。
        /// </summary>
        internal static string DateTaken {
            get {
                return ResourceManager.GetString("DateTaken", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DefaultImage {
            get {
                object obj = ResourceManager.GetObject("DefaultImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Dimensions 的當地語系化字串。
        /// </summary>
        internal static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap EmptyRatingImage {
            get {
                object obj = ResourceManager.GetObject("EmptyRatingImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Camera 的當地語系化字串。
        /// </summary>
        internal static string EquipmentModel {
            get {
                return ResourceManager.GetString("EquipmentModel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Exposure Time 的當地語系化字串。
        /// </summary>
        internal static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filename 的當地語系化字串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Path 的當地語系化字串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size 的當地語系化字串。
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 F Number 的當地語系化字串。
        /// </summary>
        internal static string FNumber {
            get {
                return ResourceManager.GetString("FNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Focal Length 的當地語系化字串。
        /// </summary>
        internal static string FocalLength {
            get {
                return ResourceManager.GetString("FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        internal static string ImageDescription {
            get {
                return ResourceManager.GetString("ImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ISO Speed 的當地語系化字串。
        /// </summary>
        internal static string ISOSpeed {
            get {
                return ResourceManager.GetString("ISOSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rating 的當地語系化字串。
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RatingImage {
            get {
                object obj = ResourceManager.GetObject("RatingImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Resolution 的當地語系化字串。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shutter Speed 的當地語系化字串。
        /// </summary>
        internal static string ShutterSpeed {
            get {
                return ResourceManager.GetString("ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Software 的當地語系化字串。
        /// </summary>
        internal static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SortAscending {
            get {
                object obj = ResourceManager.GetObject("SortAscending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SortDescending {
            get {
                object obj = ResourceManager.GetObject("SortDescending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Comments 的當地語系化字串。
        /// </summary>
        internal static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }
    }
}
