//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML2XHTML.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTML2XHTML.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] tidy {
            get {
                object obj = ResourceManager.GetObject("tidy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml {
            get {
                object obj = ResourceManager.GetObject("xhtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_attribs_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_attribs_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_base_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_base_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_bdo_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_bdo_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_blkphras_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_blkphras_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_blkpres_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_blkpres_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_blkstruct_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_blkstruct_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_charent_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_charent_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_csismap_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_csismap_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_datatypes_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_datatypes_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_edit_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_edit_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_events_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_events_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_form_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_form_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_framework_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_framework_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_hypertext_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_hypertext_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_image_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_image_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_inlphras_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_inlphras_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_inlpres_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_inlpres_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_inlstruct_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_inlstruct_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_inlstyle_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_inlstyle_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_lat1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_lat1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_lat11 {
            get {
                object obj = ResourceManager.GetObject("xhtml_lat11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_link_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_link_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_list_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_list_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_meta_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_meta_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_object_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_object_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_param_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_param_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_pres_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_pres_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_qname_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_qname_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_ruby_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_ruby_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_script_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_script_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_special {
            get {
                object obj = ResourceManager.GetObject("xhtml_special", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_special11 {
            get {
                object obj = ResourceManager.GetObject("xhtml_special11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_ssismap_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_ssismap_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_struct_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_struct_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_style_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_style_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_symbol {
            get {
                object obj = ResourceManager.GetObject("xhtml_symbol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_symbol11 {
            get {
                object obj = ResourceManager.GetObject("xhtml_symbol11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_table_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_table_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml_text_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml_text_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml1 {
            get {
                object obj = ResourceManager.GetObject("xhtml1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml1_frameset {
            get {
                object obj = ResourceManager.GetObject("xhtml1_frameset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml1_strict {
            get {
                object obj = ResourceManager.GetObject("xhtml1_strict", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml1_transitional {
            get {
                object obj = ResourceManager.GetObject("xhtml1_transitional", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml11 {
            get {
                object obj = ResourceManager.GetObject("xhtml11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhtml11_model_1 {
            get {
                object obj = ResourceManager.GetObject("xhtml11_model_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
